# Generated by Django 2.2.2 on 2019-07-01 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('styloxxi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='tags',
        ),
    ]
