# Generated by Django 2.2.2 on 2019-07-02 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styloxxi', '0004_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique_for_date='publish'),
        ),
    ]
