# Generated by Django 2.2.2 on 2019-07-02 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styloxxi', '0005_logo_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logo',
            old_name='image',
            new_name='logo',
        ),
        migrations.AddField(
            model_name='logo',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='logo',
            name='company_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
