# Generated by Django 2.2.2 on 2019-07-03 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('styloxxi', '0007_photocall'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photocall',
            old_name='image',
            new_name='image_4',
        ),
    ]
