# Generated by Django 2.2.2 on 2019-07-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styloxxi', '0008_auto_20190703_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
